[global]
    font = SauceCodePro Nerd Font 28

    width = 1000
    height = 500
    offset = 10x50

    horizontal_padding = 16

    text_icon_padding = 24

    progress_bar_min_width = 200
    progress_bar_max_width = 1000
    progress_bar_height = 30
    progress_bar_frame_width = 2
    progress_bar_corner_radius = 10

