[urgency_low]
    background = "#191311"
    foreground = "#3B7C87"
    frame_color = "#3B7C87"

    timeout = 10
    #default_icon = /path/to/icon

[urgency_normal]
    background = "#001021"
    foreground = "#FBF9FF"
    frame_color = "#726E75"
    highlight = "#FBF9FF" # changes color for progress bar
    
    timeout = 10
    override_pause_level = 30
    #default_icon = /path/to/icon

[urgency_critical]
    background = "#272838"
    foreground = "#C80036"
    frame_color = "#ff0000"

    timeout = 0
    override_pause_level = 60
    #default_icon = /path/to/icon

[volume]
    category = "volume"
    urgency = "normal"

    set_stack_tag = "x-dunst-stack-tag"

    timeout = 2

    default_icon = "/home/neo/.local/share/icons/dunst/48x48/volume_white.png"

[brightness]
    category = "brightness"
    urgency = "normal"

    set_stack_tag = "x-dunst-stack-tag"

    timeout = 2

    default_icon = "/home/neo/.local/share/icons/dunst/48x48/brightness_white.png"

