set -g default-terminal "tmux-256color"

# Remap prefix from "Ctrl-b" to "Ctrl-a"
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf

# TPM
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

### Tokyo Night Theme configuration
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @theme_variation 'storm'
set -g @theme_left_separator ''
set -g @theme_right_separator ''


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
