#!/bin/zsh

# Heavily based on gentoo prompt
# located at ~/usr/share/zsh/[version_number]/functions/Prompts/prompt_gentoo_setup

if [ "$EUID" = '0' ]
then
  local base_prompt="%B%F{red}%m%k "
else
  local base_prompt="%B%F{green}%n@%m%k 󰣨 "
fi
  local post_prompt="%b%f%k"


local path_prompt="%B%F{blue}%1~"
PS1="$base_prompt$path_prompt %# $post_prompt"
PS2="$base_prompt$path_prompt %_> $post_prompt"
PS3="$base_prompt$path_prompt ?# $post_prompt"

