import = [
    "~/.config/alacritty/themes/tokyonight_night.toml"
]

shell = "/bin/zsh"
live_config_reload = true

[window]
title = "Alacritty  "
decorations = "None"
startup_mode = "Fullscreen"

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
size = 8.5
